#!/usr/bin/env bash
# Regenerates PATTERNS.md from all patterns/*/pattern.md frontmatter
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(dirname "$SCRIPT_DIR")"
OUTPUT="${REPO_ROOT}/PATTERNS.md"

{
  echo "# Pantheon — Pattern Dispatch Table"
  echo ""
  echo "> Auto-generated by \`scripts/generate-patterns.sh\`. Do not edit manually."
  echo "> Last generated: $(date '+%Y-%m-%d')"
  echo ""
  echo "| Command | Pattern | Domain | Trigger |"
  echo "|---------|---------|--------|---------|"

  for pattern_file in "${REPO_ROOT}"/patterns/*/pattern.md; do
    gem_name=$(basename "$(dirname "$pattern_file")")
    name=$(grep "^name:" "$pattern_file" | head -1 | sed 's/^name: *//')
    domain=$(grep "^domain:" "$pattern_file" | head -1 | sed 's/^domain: *\[//' | sed 's/,.*//' | sed 's/\].*//')
    trigger=$(grep "^trigger:" "$pattern_file" | head -1 | sed 's/^trigger: *\[//' | sed 's/,.*//' | tr -d '"')
    echo "| \`/pantheon-${gem_name}\` | ${name} | ${domain} | ${trigger} |"
  done

  echo ""
  echo "---"
  echo ""
  echo "_Install: \`curl -fsSL https://raw.githubusercontent.com/dkschrei/pantheon/main/install.sh | bash\`_"
} > "$OUTPUT"

COUNT=$(grep -c "^| \`" "$OUTPUT" || true)
echo "✓ PATTERNS.md regenerated — ${COUNT} patterns"
