#!/usr/bin/env bash
# Generates PBNJ.md — the PB&J test results table
# Usage: bash scripts/generate-pbnj.sh
# Reads from tests/pbnj-outputs/*.md
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(dirname "$SCRIPT_DIR")"
OUTPUT_DIR="${REPO_ROOT}/tests/pbnj-outputs"
PBNJ_FILE="${REPO_ROOT}/PBNJ.md"

if [ ! -d "$OUTPUT_DIR" ] || [ -z "$(ls -A "$OUTPUT_DIR" 2>/dev/null)" ]; then
  echo "No PB&J outputs yet. Run: bash tests/pbnj-test.sh <pattern-name>"
  exit 0
fi

cat > "$PBNJ_FILE" << 'HEADER'
# PB&J Test Results

> **The PB&J Test** applies every Pantheon gem to one static problem: *"Construct a Peanut Butter and Jelly Sandwich."*
> Same input. Every gem. The output shows exactly what each pattern does differently — no abstractions, no theory.
> If a gem can't say something interesting about a PB&J, it can't say something interesting about your problem either.

| Pattern | The Rule | Summary | PB&J Output |
|---------|----------|---------|-------------|
HEADER

for output_file in "$OUTPUT_DIR"/*.md; do
  pattern=$(basename "$output_file" .md)
  pattern_file="${REPO_ROOT}/patterns/${pattern}/pattern.md"

  [ -f "$pattern_file" ] || continue

  # Extract trigger from frontmatter (first trigger value)
  trigger=$(awk '/^trigger:/{found=1; next} found && /^\s*-/{print; exit} found && /^[a-z]/{exit}' "$pattern_file" \
    | sed 's/^[[:space:]]*-[[:space:]]*//' | sed 's/,.*$//' | head -1)
  [ -z "$trigger" ] && trigger=$(grep "^trigger:" "$pattern_file" | sed 's/trigger: \[//' | sed 's/,.*//' | sed 's/\]//')

  # Extract The Pattern section (first 120 chars)
  summary=$(awk '/^### The Pattern/{found=1; next} found && /^###/{exit} found && NF' "$pattern_file" \
    | head -2 | tr '\n' ' ' | cut -c1-120)
  [ -z "$summary" ] && summary="—"

  # Extract PB&J output (first 180 chars after "**Output:**")
  pbnj_output=$(awk '/^\*\*Output:\*\*/{found=1; next} found && NF{print; exit}' "$output_file" \
    | cut -c1-180)
  [ -z "$pbnj_output" ] && pbnj_output="—"

  echo "| [${pattern}](patterns/${pattern}/pattern.md) | ${trigger} | ${summary}… | ${pbnj_output}… |" >> "$PBNJ_FILE"
done

echo "" >> "$PBNJ_FILE"
echo "_Generated by \`scripts/generate-pbnj.sh\`. Run \`bash tests/pbnj-test.sh <pattern>\` to add or refresh a result._" >> "$PBNJ_FILE"

COUNT=$(grep -c "^| \[" "$PBNJ_FILE" 2>/dev/null || echo 0)
echo "✓ PBNJ.md generated — ${COUNT} patterns tested"
