#!/usr/bin/env python3
"""Generates PBNJ.md — full PB&J test outputs, one section per gem, no truncation."""
import sys
import re
from pathlib import Path

REPO_ROOT = Path(sys.argv[1]) if len(sys.argv) > 1 else Path(__file__).parent.parent
OUTPUT_DIR = REPO_ROOT / "tests" / "pbnj-outputs"
PBNJ_FILE = REPO_ROOT / "PBNJ.md"

outputs = sorted(OUTPUT_DIR.glob("*.md"))
if not outputs:
    print("No PB&J outputs yet. Run: bash tests/pbnj-test.sh <pattern-name>")
    sys.exit(0)

sections = []
for output_file in outputs:
    pattern = output_file.stem
    pattern_file = REPO_ROOT / "patterns" / pattern / "pattern.md"
    if not pattern_file.exists():
        continue

    frontmatter = pattern_file.read_text()

    # Extract trigger
    trigger_match = re.search(r'^trigger:\s*\[([^\]]+)\]', frontmatter, re.MULTILINE)
    trigger = trigger_match.group(1).split(',')[0].strip().strip('"') if trigger_match else "—"

    # Extract origin-type
    origin_match = re.search(r'^origin-type:\s*(\S+)', frontmatter, re.MULTILINE)
    origin = origin_match.group(1) if origin_match else "historian"
    badge = " ✦" if origin == "authored" else ""

    # Extract full output (everything after "**Output:**")
    raw = output_file.read_text()
    output_match = re.split(r'\*\*Output:\*\*\s*\n', raw, maxsplit=1)
    output = output_match[1].strip() if len(output_match) > 1 else raw.strip()

    sections.append((pattern, badge, trigger, output))

lines = [
    "# PB&J Test Results\n",
    f"**Input:** *Construct a Peanut Butter and Jelly Sandwich*  \n",
    f"**Gems tested:** {len(sections)}\n",
    "\n",
    "> Same input. Every gem. No abstractions, no theory — just what each pattern actually does.\n",
    "> If a gem can't say something interesting about a PB&J, it can't say something interesting about your problem.\n",
    "\n---\n",
]

for pattern, badge, trigger, output in sections:
    lines.append(f"\n## {pattern}{badge}\n")
    lines.append(f"**Trigger:** {trigger}\n\n")
    lines.append(output)
    lines.append("\n\n---\n")

lines.append("\n_✦ = authored gem (written from live practice, not research)_\n\n")
lines.append("_Generated by `scripts/generate-pbnj.sh` · Refresh: `bash tests/pbnj-test.sh <pattern>`_\n")

PBNJ_FILE.write_text("".join(lines))
print(f"✓ PBNJ.md generated — {len(sections)} patterns")
